version: '3.3'
services:

  dev-dl-auth:
    container_name: dev-dl-auth
    image: dev-dl-auth
    environment:
      - SERVER_PORT=8082
      - SERVER_GRPC_PORT=7072
      - GRPC_PORT=6072
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/dev_dl_user
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
    ports:
      - 8081:8081
      - 7071:7071