version: '3.3'
services:

  dev-dl-blog:
    container_name: dev-dl-blog
    image: dev-dl-blog
    environment:
      - SERVER_PORT=8080
      - SERVER_GRPC_PORT=7070
      - GRPC_PORT=6070
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/dev_dl_blog
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword
    ports:
      - 8080:8080
      - 7070:7070