version: "3"
services:

  zookeeper-1:
    container_name: zookeeper-1
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOO_PORT_NUMBER=2181
      - ALLOW_ANONYMOUS_LOGIN=yes

  zookeeper-2:
    container_name: zookeeper-2
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2182:2182'
    environment:
      - ZOO_PORT_NUMBER=2182
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    container_name: kafka-1
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-1

  kafka-2:
    container_name: kafka-2
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-2:2182
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-2