server:
  port: ${SERVER_PORT:8080}
  grpc:
    port: ${SERVER_GRPC_PORT:7070}
    server: ${SERVER_GRPC_SERVER:static://localhost:7070}
#grpc:
#  server:
#    port: ${GRPC_PORT:6000}
spring:
  application:
    name: Coz Contact
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/contact}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
kafka:
  server: ${KAFKA_SERVER:PLAINTEXT://localhost:9092}
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
  sasl:
    mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
    jaas:
      config: ${KAFKA_SASL_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required;}
    client:
      callback:
        handler:
          class:
  topic-reminder: facehub-reminder
  topic-reply: facehub-reply
  numPartitions: 2
  replicationFactor: 1
  group-id: facehub-cozwork
