server:
  port: ${SERVER_PORT:8082}
grpc:
  server:
    port: ${GRPC_PORT:7082}
security:
  jwt-secret: OIASUD098asdoiuasdqwoeiusad0opaisd
  jwt-expiration: 10
spring:
  application:
    name: Dev-DL-Authenticate
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_dl_user}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER