server:
  port: 8080
  grpc:
    user-server: ${SERVER_GRPC_SERVER:static://localhost:7081}
grpc:
  server:
    port: ${GRPC_PORT:7080}
spring:
  application:
    name: Dev-DL-Blog
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_dl_blog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 10
          max-interval: 30000
          multiplier: 3.0
rabbit:
  queue:
    blog: rabbit-blog
  route:
    key: blog-route-key
direct:
  exchange:
    name: blog-direct-exchange
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    enabled: false