server:
  port: 8080
  grpc:
    user-server: ${SERVER_GRPC_SERVER:static://localhost:7081}
grpc:
  server:
    port: ${GRPC_PORT:7080}
spring:
  application:
    name: Dev-DL-Blog
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_dl_blog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  graphql:
    graphiql:
      enabled: true
      path: /graphiql