server:
  port: 8080
  grpc:
    port: ${SERVER_GRPC_PORT:7070}
    server: ${SERVER_GRPC_SERVER:static://localhost:7071}
grpc:
  server:
    port: ${GRPC_PORT:6070}
spring:
  application:
    name: Coz Contact
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_dl_blog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER