server:
  port: ${SERVER_PORT:8081}
  grpc:
    auth-server: ${SERVER_GRPC_AUTH_SERVER:static://localhost:7082}
grpc:
  server:
    port: ${GRPC_PORT:7081}
spring:
  application:
    name: Dev DL User
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_dl_user}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
